# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    strategy:
      matrix:
        node-version: [22]  # see https://nodejs.org/en/about/releases/
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'  # only if package-lock is present

    - run: npm ci

    - name: Node
      run: npm run node-test

    - name: Jest
      run: npm run jest

    - name: Mocha
      run: npm run mocha

    - name: Chest
      if: runner.os != 'Windows'
      run: npm run chest
