name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  test:
    strategy:
      matrix:
        node-version: [22, 24]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'sapmachine'
          cache: maven

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm ci

      - name: Install Java app npm dependencies
        run: npm ci
        working-directory: test/runtime/java/app

      - name: Maven package
        run: mvn -f test/runtime/java/app/pom.xml package -DskipTests -e

      - name: Node Test Runner
        run: npm run node-test

      - name: Jest
        run: npm run jest

      - name: Vitest
        run: npm run vitest

      - name: Mocha
        run: npm run mocha

      - name: Chest
        run: npm run chest

      - name: Axios installed
        run: |
          npm i axios -D
          npm run node-test
          git checkout package.json
